### ISSUE TITLE
cannot find gradle dependency

### ISSUE THREAD

**Issue by j2emanue** [Tinder/StateMachine#1]
which repository is in it ? i tried putting in android studio but i get gradle reporting that it cannot resolve it?

`
Failed to resolve: com.tinder:state-machine:0.0.1`

im using these ones: 

```
 jcenter()

        maven { url 'https://maven.fabric.io/public' }
        mavenCentral()
        google()
```

**Comment by zhxnlai** [comment]
@j2emanue Thanks for reporting the issue. We are still in the progress of pushing it to Bintray. Stay tuned!

**Comment by zhxnlai** [comment]
@j2emanue I am glad to let you know that StateMachine is now available via [JitPack](https://jitpack.io/#tinder/statemachine/) while we work on publishing it to Bintray
