### ISSUE TITLE
A Visualizer for state machine

### ISSUE THREAD

**Issue by nvinayshetty** [Tinder/StateMachine#13]
Hey, thanks for all the great work.  I really like using State Machine DSL in my daily work.
I have created an IntelliJ plugin to visualize the StateMachine. While I'm waiting for the review process by IntelliJ to complete for it to publicly available, could you share your opinion/ feedback on my work here
https://github.com/nvinayshetty/StateArts

**Comment by zhxnlai** [comment]
@nvinayshetty This is impressive! Can't wait to try it. Could you keep me updated when it is publicly available? I am wondering if this plugin can reveal to the user the dot file generating the png.

**Comment by nvinayshetty** [comment]
@zhxnlai the plugin is publicly available now!. To install in android studio goto
AndroidStudio->preferences->plugins->browse repositories->search for "State Art" .
this plugin works based on Graphviz, so make sure you have Graphviz installed in the path.

Yes this plugin reveals dot file to the user.
The dot file will be available at `build/stateArt/States `. The dot file will be generated only after the line marker icon is double cliked

**Comment by nvinayshetty** [comment]
@zhxnlai Do you mind leaving a link to StateArts plugin/Repo in the StateMachine GitHub repo as a support tool? so that it will be easier to  StateMachine DSL users to find the tooling support they need?

**Comment by zhxnlai** [comment]
@nvinayshetty Sure. I will update the README. 

However, I wasn't able to install the plugin through intellij IDEA due to network error (probably on their side)
<img width="1010" alt="Screen Shot 2019-04-04 at 10 01 36 AM" src="https://user-images.githubusercontent.com/4694896/55574236-ca583a00-56c0-11e9-9015-47e13ec15cf8.png">
<img width="1008" alt="Screen Shot 2019-04-04 at 10 01 41 AM" src="https://user-images.githubusercontent.com/4694896/55574235-ca583a00-56c0-11e9-8b1d-9c6709c53d07.png">

I got around it by [downloading](https://plugins.jetbrains.com/plugin/12193-state-art) the plugin and install from disk

**Comment by zhxnlai** [comment]
Do you plan to support visualizing Side Effect?

**Comment by nvinayshetty** [comment]
> @nvinayshetty Sure. I have updated the README.
> 
> However, I wasn't able to install the plugin through intellij IDEA due to network error (probably on their side)
> <img alt="Screen Shot 2019-04-04 at 10 01 36 AM" width="1010" src="https://user-images.githubusercontent.com/4694896/55574236-ca583a00-56c0-11e9-9015-47e13ec15cf8.png">
> <img alt="Screen Shot 2019-04-04 at 10 01 41 AM" width="1008" src="https://user-images.githubusercontent.com/4694896/55574235-ca583a00-56c0-11e9-8b1d-9c6709c53d07.png">
> 
> I got around it by [downloading](https://plugins.jetbrains.com/plugin/12193-state-art) the plugin and install from disk

That's weird, Hope you were able to use it just fine. Thanks for updating the readme

**Comment by nvinayshetty** [comment]
> Do you plan to support visualizing Side Effect?

Not in my immediate plans. I think it might clutter the visualization, I will defnitely consider adding such a feature if it makes the overall workflow better
I will see if I can help in adding things like `BaseState` and  `multiTransition` to the DSL

**Comment by nvinayshetty** [comment]
Please close the issue if you don't have any other concerns
