### ISSUE TITLE
Useful as a UI Architecture?

### ISSUE THREAD

**Issue by carterhudson** [Tinder/StateMachine#4]
~~Is it possible to attach data to states and events using the DSL? I've been avoiding using Mobius or RxRedux for implementing state machines as part of UI architecture and just writing my own. I'd like to use this DSL to describe my state machines for the sake of formalization and reusability, but I can't see a way to make my states and events meaningful in terms of attaching data to them. Should I just write my own DSL that suits my needs? :[~~

~~Edit: For clarification, my pain point is when I'm declaring states to transition to. The `transitionTo` builder method wants a state instance, but the state instance, in my case, can only be constructed once an event with a payload is received and parsed. Is it possible to access the event that caused the transition when declaring the `transitionTo`, perhaps in the scope of `on<SomeEvent> { ... }`?~~

Turns out you can optionally specify the presence of an event parameter for the lambda of `on<SomeEvent> { ... }`. Sneaky.

Another question, then - are SideEffects triggering new Events supported with this DSL? I don't see an obvious way to dispatch new events in `onTransition { ... }` since the state machine isn't created yet.

**Comment by zhxnlai** [comment]
@carterhudson There are two ways to receive side effects:
1. adding an `onTransition` callback. The callback can invoke a method, trigger a listener, or write to a stream whose subscriber will execute the side effect
2. using the return value of `StateMachine#transition` method. This method synchronously returns a `Transition` object, which can be passed to an object that executes the side effect

**Comment by bbil** [comment]
@carterhudson 

The way I've maneuvered around triggering events where the state machine isn't created yet is to have a wrapper class.

```
class StateMachineWrapper {
    fun transition(event: Event) {
        this.sm.transition(event)
    }

    val sm = StateMachine.create<> {
         // blah
         onTransition {
              this@StateMachineWrapper.transition(Event.Whatever)
         }
    }
```

**Comment by davrukin** [comment]
> @carterhudson There are two ways to receive side effects:
> 
> 1. adding an `onTransition` callback. The callback can invoke a method, trigger a listener, or write to a stream whose subscriber will execute the side effect
> 2. using the return value of `StateMachine#transition` method. This method synchronously returns a `Transition` object, which can be passed to an object that executes the side effect

Can you please give an example of both? I’m not entire sure on how to “execute” the transition if I capture the return

**Comment by radekkozak** [comment]
> Turns out you can optionally specify the presence of an event parameter for the lambda of on<SomeEvent> { ... }. Sneaky.

Hi Carter, would you be so kind to explain this more ? 

I struggle with same thing: i need to get access to the event instance when declaring the `transitionTo` simply because some of my events carry a value. I got around it some other way but your sentence suggests that maybe i'm missing something here

In other words

`on<SomeEvent> { 
 // how to access SomeEvent instance here
 }`

Thanks in advance 
/cc @zhxnlai
