### ISSUE TITLE
StateMachine `v0.3.0` isn't available in Maven Central

### ISSUE THREAD

**Issue by mozesa** [Tinder/StateMachine#55]
![image](https://user-images.githubusercontent.com/49973426/186589127-433687a7-f36e-40b6-81e2-0f67cf9a363d.png)

**Comment by GuilhE** [comment]
True, I've created a PR https://github.com/Tinder/StateMachine/pull/43 but it seams this library it's stale... I'll be moving forward to this one: https://freeletics.github.io/FlowRedux/

**Comment by aaronweihe** [comment]
0.3.0 is for the swift binary. we are looking to streamline publishing both version numbers.
